### ISSUE TITLE
Barriers to self-hosting

### ISSUE THREAD

**Issue by iexos** [Safiyya/circlemapping#811]
Hi,
I tried Maptio and it looks great, very much like what we need for the self-organized community I am in. I would love to integrate Maptio into our self-hosted platform consisting of FOSS tools, though there are a few issues blocking that:

1. Depends on other proprietary cloud services (Cloudinary, Auth0, maybe more?). There is no point in self-hosting if we still rely on external services.
2. No easy self-hosting option, i.e. missing maintained docker image. Ideally with a sample docker-compose file to set the whole stack up.

Also the documentation could use some improvement, as you have stated in the readme already :)
I could have opened seperate issues for this, but I would like to use this thread to discuss if you are actually interested in making changes for easy self-hosting and supporting the development of a FOSS community around this project. I'd be happy to hear about your feedback!

**Comment by rgoj** [comment]
Thank you for raising the issue, @iexos ! We've had a few requests around this since going open source already, but haven't been able to prioritise making Maptio easier to self-host so far - but the more votes we get on this, the easier it will be for us to do so, so thank you!

In my mind Maptio is only partially open source now - if you can't just easily run it locally with docker / simple instructions, can't do so without relying on external proprietary cloud services (the two biggest ones are Auth0 and Intercom), there are no guidelines for contributors, etc., then we're not _fully_ open source yet.

We're small and there's so much we want to do! (I'm the only developer working on the project right now - I'm lucky to be paid to do so, but still there's only so much time!)

Our big hope with the open sourcing has been and still is that somebody might be able to step in with the resources to refactor away our dependencies on Auth0, Intercom, etc. We'd of course love to help, but haven't been able to take this on ourselves yet. We've had some discussions with people about this and @tomnixon, Maptio's founder, is actively looking for organisations that might be interested.

The second hope is that we become self-sustainable (i.e. from revenue from the hosted version of Maptio) and so can have more space to do all of the work necessary to make Maptio really feel like an open source product too. But for that we need to focus on functionality and features.

It's a tough balancing act, in other words. Apologies I couldn't reply with anything more, but I will raise this issue in our discussions of priorities and hopefully it'll be a contribution towards us committing time to this sooner rather than later, so thank you for opening it!

**Comment by samuk** [comment]
+1 for a Docker. 

It could probably be hosted on https://recipes.coopcloud.tech/ then.

**Comment by rgoj** [comment]
> +1 for a Docker.

Thanks for the vote, @samuk, the first steps are already here (thanks to @piotr-sikora-v): https://github.com/Maptio/maptio/pull/820

> It could probably be hosted on https://recipes.coopcloud.tech/ then.

Nice, thank you!

**Comment by mohb-ellakani98** [comment]
Hi everyone,
I was trying to install maptio and I was following the instructions and when I run npm start I get many warnings regarding circular dependencies such as these : 

(node:25753) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:25753) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:25753) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

And if I try to access this URL : http://localhost:4200 I get nothing and if I access http://localhost:3000 which is the one that I get in the terminal it tells me cannot /GET

Does anyone have an idea on how to fix this.

Thank you.

**Comment by rgoj** [comment]
Hi @mohb-ellakani98 , thank you for your interest in Maptio and for trying to set it up locally!

As mentioned above, sadly we just don't have the resources at the moment to spend the time on clearing the obstacles to setting Maptio up locally, to remove dependencies on Auth0, Intercom, etc. Sadly! One day hopefully we'll get to that place to be able to prioritise this. Or, hopefully, someone in the community manages to! The wonderful folks from https://ftdl.pl/ are trying to help with this, but it is a large, time-consuming task!

Meanwhile, to answer your questions directly:
1. Re. the sad flood of warnings about circular dependencies - I need to tackle those one day, but they shouldn't prevent Maptio from working for you locally.
2. Re. the other issues - I haven't set up Maptio completely from scratch in a very long time, so I can't say for sure. My best bet would be that you don't have the required keys for external dependencies in a `.env` file? (i.e. a copy of the sample file added in #824). For this you'll need to set up accounts with Auth0 and Intercom, likely others. Have you tried that?

**Comment by mohb-ellakani98** [comment]
Hi @rgoj 
As for the circular dependencies they can be easily ignored and don't stop the execution of the code as for the .env file I have created it and created an account on Auth0 and Intercom and have added the needed keys but I still got the same error

**Comment by rgoj** [comment]
@mohb-ellakani98 Ah, brilliant that you've gone as far as handling the Auth0 and Intercom keys! (Though, obviously, not so brilliant that you had to do that in the first place, sorry for that...)

Perhaps you could post the full output of running `npm start`? Better yet, please run the server and the front-end app separately with `nx serve maptio-server` and `nx serve maptio` and post the outputs here.

Also, if you are running into a localisation issue when serving the front-end app, set `localize` to `false` in `angular.json`. I'll push a PR with that fix for this misconfiguration in a moment, I've been meaning to do this for a long time, so thanks for the nudge!

**Comment by mohb-ellakani98** [comment]
I'll give you the outputs to all three so that you can have a better look at these problems and maybe this insight might be helpful for you.

npm start :
$ npm start

> maptio@2.0.0 start
> nx run-many --target=serve --projects=maptio,maptio-server --parallel


 >  NX   Running target serve for 2 projects:

    - maptio
    - maptio-server

 —————————————————————————————————————————————————————————

> nx run maptio:serve


> nx run maptio-server:serve

assets by path assets/templates/*.liquid 19.6 KiB
  asset assets/templates/invitation-email.liquid 19.2 KiB [emitted] [from: src/assets/templates/invitation-email.liquid] [copied]
  asset assets/templates/invitation-subject.liquid 353 bytes [emitted] [from: src/assets/templates/invitation-subject.liquid] [copied]
asset assets/templates/maps/demo.json 46.7 KiB [emitted] [from: src/assets/templates/maps/demo.json] [copied]
asset main.js 43 KiB [emitted] (name: main) 1 related asset
cacheable modules 36.4 KiB
  modules by path ./src/routes/ 23.6 KiB
    ./src/routes/datasets.js 2.78 KiB [built] [code generated]
    ./src/routes/embeddable-datasets.js 1.25 KiB [built] [code generated]
    ./src/routes/users.js 4.31 KiB [built] [code generated]
    + 8 modules
  modules by path ./src/i18n/*.ts 1.86 KiB
    ./src/i18n/get-locale-from-path.ts 427 bytes [built] [code generated]
    ./src/i18n/get-closest-supported-locale.ts 1.44 KiB [built] [code generated]
  modules by path ./src/auth/*.ts 1.06 KiB
    ./src/auth/management-client.ts 756 bytes [built] [code generated]
    ./src/auth/config.ts 327 bytes [built] [code generated]
  ./src/main.ts 9.47 KiB [built] [code generated]
  ./src/environments/environment.ts 363 bytes [built] [code generated]
+ 22 modules
webpack 5.75.0 compiled successfully in 608 ms
Debugger listening on ws://localhost:9229/7d96cfed-a3a5-4caf-aae6-7d98bcdfd687
Debugger listening on ws://localhost:9229/7d96cfed-a3a5-4caf-aae6-7d98bcdfd687
For help, see: https://nodejs.org/en/docs/inspector
Type-checking in progress...
⠋ Generating browser application bundles (phase: setup)...
 >  NX   The development server only supports localizing a single locale per build.

   Pass --verbose to see the stacktrace.

(node:68267) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68267) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'Symbol(Symbol.toStringTag)' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'length' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'config' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'utils' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'uploader' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'api' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'PreloadedFile' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'url' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'image' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'video' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'cloudinary_js_config' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'CF_SHARED_CDN' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'AKAMAI_SHARED_CDN' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'SHARED_CDN' of module exports inside circular dependency
(node:68267) Warning: Accessing non-existent property 'BLANK' of module exports inside circular dependency
==> 🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
No errors found.


nx server maptio-server:
I modified the run command to use npx 

npx serve maptio-server
Need to install the following packages:
  serve@14.2.1
Ok to proceed? (y) y

   ┌────────────────────────────────────────────┐
   │                                            │
   │   Serving!                                 │
   │                                            │
   │   - Local:    http://localhost:3000        │
   │   - Network:  http://10.199.226.127:3000   │
   │                                            │
   │   Copied local address to clipboard!       │
   │                                            │
   └────────────────────────────────────────────┘

 HTTP  9/6/2023 3:54:49 PM ::1 GET /
 HTTP  9/6/2023 3:54:49 PM ::1 Returned 404 in 13 ms
 HTTP  9/6/2023 3:54:49 PM ::1 GET /favicon.ico
 HTTP  9/6/2023 3:54:49 PM ::1 Returned 404 in 2 ms
 HTTP  9/6/2023 3:54:51 PM ::1 GET /
 HTTP  9/6/2023 3:54:51 PM ::1 Returned 404 in 2 ms

nx server maptio:
Also here I modified it to use npx

npx serve maptio

   ┌────────────────────────────────────────────┐
   │                                            │
   │   Serving!                                 │
   │                                            │
   │   - Local:    http://localhost:3000        │
   │   - Network:  http://10.199.226.127:3000   │
   │                                            │
   │   Copied local address to clipboard!       │
   │                                            │
   └────────────────────────────────────────────┘

 HTTP  9/6/2023 3:56:06 PM ::1 GET /
 HTTP  9/6/2023 3:56:06 PM ::1 Returned 404 in 10 ms





Hope that modifying the command to npx is not an issue and that these results can help you and me.

**Comment by rgoj** [comment]
Brilliant, thanks @mohb-ellakani98 ! (By the way, I took the liberty of editing your post with some markdown to make the output easier to distinguish from your words.)

So, the issue is indeed localisation-related. The hint is here in the output of `npm start`:

```
 >  NX   The development server only supports localizing a single locale per build.
```

Please pull from master to get the changes from #834 and try again, hopefully that should help!

> Hope that modifying the command to npx is not an issue and that these results can help you and me.

Those commands do require `nx` rather than `npx`. We use [Nx](https://nx.dev/) for monorepo scaffolding and to get some good, modern defaults for Angular development, hence the need for using the `nx` command. You can run it with `npx nx` too if you don't have it installed locally. In hindsight, that's the command I should've given you.

Still, the output of `npm start` was enough to diagnose the error, so thanks for that! It seems that the server is starting up correctly too, which is great. Now, let's hope the front-end app starts up too and let's see what happens when the two start communicating!

**Comment by mohb-ellakani98** [comment]
Ok so I did a pull from the master branch and indeed now the website runs at least as a home page but I face 2 new problems.

1- npx nx serve maptio-server and npm start both need port 3000 to work so if you could point me to where to change one or the other.

2- npx nx server maptio --verbose

 >  NX   Cannot find configuration for task maptio:server


Error: Cannot find configuration for task maptio:server
    at ProcessTasks.createTask (/home/ellakani/Documents/maptio/node_modules/nx/src/tasks-runner/create-task-graph.js:101:19)
    at ProcessTasks.processTasks (/home/ellakani/Documents/maptio/node_modules/nx/src/tasks-runner/create-task-graph.js:21:39)
    at createTaskGraph (/home/ellakani/Documents/maptio/node_modules/nx/src/tasks-runner/create-task-graph.js:136:21)
    at /home/ellakani/Documents/maptio/node_modules/nx/src/tasks-runner/run-command.js:83:71
    at Generator.next (<anonymous>)
    at /home/ellakani/Documents/maptio/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/ellakani/Documents/maptio/node_modules/tslib/tslib.js:113:16)
    at /home/ellakani/Documents/maptio/node_modules/nx/src/tasks-runner/run-command.js:79:114
    at /home/ellakani/Documents/maptio/node_modules/nx/src/utils/params.js:10:26

Hope these can help and maybe my inquiries help other developers in running maptio locally

**Comment by mohb-ellakani98** [comment]
Another issue I just encountered is that the page that is loaded disappears and shows for a second when refreshing but it does not remain.

**Comment by rgoj** [comment]
> Ok so I did a pull from the master branch and indeed now the website runs at least

Brilliant! Well done getting to this point!

>npx nx serve maptio-server and npm start both need port 3000 to work so if you could point me to where to change one or the other.

`npm start` is configured to run both the server and the front-end app. You can see this in the `package.json` file where that command is defined:

```
(...)
"start": "nx run-many --target=serve --projects=maptio,maptio-server --parallel", 
(...)
```

You can run the backend and the front-end separately, if you choose, by running `npx nx serve maptio` and `npx nx serve maptio-server` (which is sometimes useful for debugging errors, etc.) but you don't need to run all three at once. Does that help? 

> npx nx server maptio --verbose

The issue here is a typo - the Nx commad is `serve` not `server`, i.e. the full command should be `npx nx serve maptio --verbose`

If you simply run just `npm start` without running the other commands, does that help? What errors are you seeing then?

**Comment by rgoj** [comment]
~Hmm, I can't seem to figure out what could be going wrong, sadly! It does seem to be related to login errors, suggesting a possible Auth0 misconfiguration... but I have a very low degree of confidence in that guess! The content of the browser console error (`this.router` not being defined in `user.service`) is odd. Is that the only error in the console? That call to `this.router` is preceded by `console.error(error)` in the `handleLoginError` method, so I'd have expected another error to be in the console before the call `this.router` failed). And I'm not sure why that could would even be running in the first place since you haven't had the chance to attempt to log in via the app.~

~Certainly there's some failure of communication - the `ECONNREFUSED` error - but where exactly, I don't have any good ideas yet.~

~I'd suggest we jump on a call (booking link in reply to your support request), I'm not that good at async debugging and on a call we can try a lot of things a lot more quickly!~
 
Right. As I was writing all of the above (still worth reading, so keeping it here), I found a way to at least reproduce the `Cannot read properties of undefined (reading 'navigateByUrl')` error and so fixed that one at least (see #835). Please pull from master and try again. You should still see an error in the browser, but this time it should be clearer what the real error is. Hopefully. I still think it'd be faster to try debugging on a call (and then posting results here, obviously) - I suspect we'll need to look at what's in your `.env` exactly eventually, which it's probably best not to post here - but I'm happy to at least try to continue this way and see how far we get. In any case, thanks for your efforts, it's helping identify and fix problems others will be / are running into!

**Comment by mohb-ellakani98** [comment]
Hi @rgoj ,

Thank you so much I made a pull request and indeed this fixed the page from not showing any content but as always with development new errors have emerged now when I try to login with Google or with my email and password or create a new account so simply try and login to use the software locally I get a login error page that says this :

A login error occurred
Despite our best efforts, things will sometimes break, but we are always happy to help get you back on track.
Chat with us or email us at support@maptio.com if the issue persists.

In the console I get this error :
GET http://localhost:4200/api/v1/user/google-oauth2%7C110520379052413084757 500 (Internal Server Error)

And in the terminal I get this error : 
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
 
I don't have any problem in jumping in a meeting but during the week I am not free to do so, so if in the weekend you are free I would be more than happy to jump in a meeting with you and try and solve this issue.

**Comment by rgoj** [comment]
Brilliant that we're getting to the real errors now! (And not just stumbling on the bugs I wrote!)

Hmm. Thinking out loud here. That `GET` request to Maptio's API is for information about your user based on your Google OAuth ID. You seem to be getting a 500 response from the server to this request, I'm assuming that's due to the `ECONNREFUSED` error happening server-side.

Hmm. Will be interesting to find out what's causing this!

The one thing that comes to mind at this point that we haven't looked at yet would be - are you seeing successful connections to your local MongoDB instance? That request to `http://localhost:4200/api/v1/user/...` should trigger a query from the server to the DB, so, if everything is going alright, you should be able to see that happening if you're also looking at MongoDB logs. Can you see anything helpful there? Any errors even before you try to log in? Then, as you start the login process, can you see any new log entries? If so, anything interesting in those entries? If not, that tells us that the server can't communicate with the database (or, alternatively, is not even reaching that point, though it does appear to be trying to communicate with something judging by the `ECONNREFUSED` errors!).

Another thing that you could try is to debug the server-side code - just `console.log` your way into more information about what might be happening in this (I think) bit of code: https://github.com/Maptio/maptio/blob/master/apps/maptio-server/src/routes/users.js#L67

> I don't have any problem in jumping in a meeting but during the week I am not free to do so, so if in the weekend you are free I would be more than happy to jump in a meeting with you and try and solve this issue.

Cool, that makes sense. I've added some availability to that calendly link I sent you via the support channel on Sunday afternoon - if you can't make any of those times, let me know what might work better for you and I'll see if I can't make that!

**Comment by rgoj** [comment]
Thanks for the call earlier today, @mohb-ellakani98 !

I'll write up where we got to for anyone who might be reading this and also for my future self. TL;DR: The problem is not yet fixed, but we've gone through a few more steps, so it's worthing noting these!

1. Firstly, when you set up an Auth0 account, it's worth going through the Auth0 documentation to get everything set up in Maptio: https://auth0.com/docs/quickstart/spa/angular/01-login (the instructions for Maptio will be slightly different, we need to write those up, but this can give you a sense of what's needed)
2. You will need to create two applications for your Auth0 tenant - one for the front-end code and one for the backend code. The latter will be an API application.
3. The front-end application needs to be of the "Single Page Application" type.
4. You will need to change `auth.domain` as well as `clientId` inside of `environment.ts` to the values you find in the settings for your front-end Auth0 application.
5. You will also need to set the following (in those same settings):
```
Allowed Callback URLs
http://localhost:4200/login, http://localhost:3000/login

Allowed Logout URLs
http://localhost:4200/logout, http://localhost:3000/logout

Allowed Web Origin
http://localhost:4200, http://localhost:3000
```
6. In the API application for Auth0, you will need to set the identifier to `http://localhost:4200/api/v1`
7. Then, you will need to add an `api` permission in the Permissions tab.

We need a more comprehensive write-up, I think. And, of course, ideally, a way to run the app locally without Auth0 - or with an already set up instance of an open source solution via Docker. For now, I hope this helps, or, possibly serves as a good starting point for others.

With all of the above, we got to Auth0 working correctly... but when you're returned to the application, we still saw 500 errors on login, so still need to dig in deeper beyond what we've got to here!

**Comment by VincentSC** [comment]
I think I can get this working with Keycloak, so that removes auth0-dependency. But before I make a PR, I first need to get it running for the rest.

One thing I find difficult is what exactly in the `.env` must be filled. 

Where does this error come from? `Error: ENOENT: no such file or directory, open '/app/dist/apps/maptio-server/assets/id_rsa'`
I just created SSH-keys in `apps/maptio-server/src/assets` without password, and did a `mv id_rsa.pub rsa.pub` to comply with the naming convention used in the app. It seems to work...

Where exactly is intercom used for? Only for pushing messages to apps? Can this functionality easily be turned off?

**Comment by rgoj** [comment]
> I think I can get this working with Keycloak, so that removes auth0-dependency.

That would be so cool, thank you! 🤩 

> One thing I find difficult is what exactly in the `.env` must be filled.

Yes... I'm just working on an update to the README that should be out by Wednesday. Mainly to allow people to set up their own Auth0 tenant (might be relevant for you too if you'd like to go down the route of first setting everything up with Auth0 & Intercom).

> Where does this error come from? `Error: ENOENT: no such file or directory, open '/app/dist/apps/maptio-server/assets/id_rsa'`
> I just created SSH-keys in `apps/maptio-server/src/assets` without password, and did a `mv id_rsa.pub rsa.pub` to comply with the naming convention used in the app. It seems to work...

Good point, I'm pretty sure we can remove all the code around this - one of the many tech debty things I never get the chance to do! It's basically old auth code we don't rely on anymore (unless I'm mistaken, will be certain when I trace everything and get the app working without the code).

> Where exactly is intercom used for? Only for pushing messages to apps? Can this functionality easily be turned off?

Sadly, we do store information about organisation accounts in Intercom... part of the initial design of Maptio - to use external services to get to a working prototype as fast as possible. Something that worked well initially, but we're working on refactoring now. The relevant issue is here for a bit more context: #615 There's no easy switch to just turn this off, but this should be easier than all the auth work to remove the Auth0 dependency.

Thanks again for giving Maptio a spin, hugely appreciated!

(Sorry for editing your post - went in there to copy your text for replies and enthusiastically started editing that instead of pasting into a new post. Definitely excited about any interest in Maptio obviously! 😅)

**Comment by VincentSC** [comment]
Thanks for the quick reply!

Auth0 has a rather clean implementation of oAuth2, so I seriously think it's not a big thing to do. If Keycloak works, then any oAuth2-provider will work. 

And if Intercom removal (and thus rewriting all the code to use the DB) is easier than then Auth0-dependency, w'll have it all going by February :) 

But... my guess it's really better for me to wait for issue 615 to finish, before moving further. I want to focus on things I know....

Another dependency is on Slack, and this can be replaced by Mattermost. This is not so difficult to do, and hopefully triggers others to support other popular chat-systems.

**Comment by rgoj** [comment]
> Auth0 has a rather clean implementation of oAuth2, so I seriously think it's not a big thing to do. If Keycloak works, then any oAuth2-provider will work.
> 
> And if Intercom removal (and thus rewriting all the code to use the DB) is easier than then Auth0-dependency, w'll have it all going by February :)
> 
> But... my guess it's really better for me to wait for issue 615 to finish, before moving further. I want to focus on things I know....

I think Tom already got in touch about scheduling a call, it'd be cool to talk this through. We've not currently scheduled the intercom work, but knowing someone's up for creating a branch with an open source auth solution would definitely help us move priorities up.

> Another dependency is on Slack, and this can be replaced by Mattermost. This is not so difficult to do, and hopefully triggers others to support other popular chat-systems.

We don't actually depend on Slack in any way, that's old code hanging around from old functionality we offered years ago, before my time - now removed from master - thanks for the prompts to do a bit of cleaning up!

**Comment by rgoj** [comment]
A small update on our side, we've just added some instructions for setting up an Auth0 tenant (see changes in #867), with configs that can be imported using the Auth0 CLI tooling and a bit of documentation in the README. Very far from perfect, but, hopefully, a small step forward!

**Comment by bokkoman** [comment]
I prefer seeing a docker image of this as well.

**Comment by rgoj** [comment]
> I prefer seeing a docker image of this as well.

Thanks for the feedback, @bokkoman !

An update on our side - making meaningful progress on this issue is one of main priorities right now (largely thanks to all the engagement in this thread, so thank you for that!). We don't have time frame estimates, but hopefully there'll be some progress to share here sooner rather than later.

**Comment by bokkoman** [comment]
What exactly are you missing to create a docker image out of it? 
Preferably, i would also suggest not relying on external auth? As in, make it an option, but make an internal user system as well. 
(Unless it already is, i haven't got it to work yet).

**Comment by bokkoman** [comment]
1. You can look at just local users in the app, stored in a db (hashed of course).
2. Have SAML and/or OAUTH.
3. Use LDAP.
4. Rely on a third party user tool? Something like Authentik? Which can also incorporate all the above.

**Comment by rgoj** [comment]
> 4. Rely on a third party user tool? Something like Authentik? Which can also incorporate all the above.

This is not one I've come across yet, thanks for the recommendation, an option to consider!

**Comment by vinicius507** [comment]
Is Intercom required right now? Is there no way to deploy maptio without Intercom?

**Comment by rgoj** [comment]
Yes, both Intercom and Auth0 are currently required, unfortunately. We're now aiming to prioritise removing these dependencies for local setups and I hope to be able to start working on this soon - as soon as a health issue that's been bugging me clears up, hopefully very soon! 🤞🏻

**Comment by Xemnas0** [comment]
Hi!
I've managed to setup Auth0 as described in the README.md, I signed up a new user, but when I try to login I get this error on the docker compose logs

app-1  |  Error: getaddrinfo ENOTFOUND dev-<MY_DOMAIN>.eu.auth0.com.well-known
app-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

As well "A login error occurred" on the frontend page.

Does anyone have any idea on what could be the problem? Thank you!

**Comment by Xemnas0** [comment]
Hi @rgoj, thank you the reply.
I hope you rest well and recover!

I was dumb enough to forget a final "/" on the AUTH0_ISSUER, and that was giving the problem.

I managed to set up Auth0 and initialize the variables for Intercom, and everything seems to be running correctly!

Few notes:
- It seems like every user is forced, on first login, to create an organization. Is there a way to avoid that and make that automatically assigned to the only organization that is gonna live in our instance?
- Can the entire website run without Intercom, or there's some main feature that might break?

We are an environmental activism group that are trying to set up a private instance of Maptio. We are really grateful that such platform exist, so thanks a lot for your hard work!

**Comment by rgoj** [comment]
> I managed to set up Auth0 and initialize the variables for Intercom, and everything seems to be running correctly!

Fantastic to hear that you got Maptio up and running, @Xemnas0 ! Congrats on finding the source of the problem!

> It seems like every user is forced, on first login, to create an organization. Is there a way to avoid that and make that automatically assigned to the only organization that is gonna live in our instance?

Yeeesss. It might not be trivial, but, in essence:
* the check for whether to create an organisation happens here: https://github.com/Maptio/maptio/blob/master/apps/maptio/src/app/modules/home/pages/home/home.page.ts#L81-L84
* instead of opening the onboarding you could fetch a particular hardcoded team and add that user to the team
* the code for adding users to a team lives, roughly, here: https://github.com/Maptio/maptio/blob/master/apps/maptio/src/app/shared/services/user/user.service.ts#L264 though it would need to be modified
* there's definitely complexities involved in some of the code there, but it should be doable with some trial and error!

> Can the entire website run without Intercom, or there's some main feature that might break?

The only real thing we really on intercom for is checking subscription / free trial status. The rest is just the intercom chat itself and old analytics calls which we're not really relying on. So, in other words, all you might need to change is hardcoding values for your organisation here instead of the call to the intercom API: https://github.com/Maptio/maptio/blob/master/apps/maptio/src/app/shared/services/billing/billing.service.ts#L16 That might not be enough, but it should get you started. The other intercom functionality will break on disconnecting from intercom, but it should be a simple case of running through the code and removing anything that breaks. Unless I'm missing stuff, which is always highly likely :)

> We are an environmental activism group that are trying to set up a private instance of Maptio. We are really grateful that such platform exist, so thanks a lot for your hard work!

Well, we are grateful for anyone involved directly in working to save our environment - thank you! It's a pleasure for us (and the whole purpose of Maptio, really) to be contributing in some small way to valuable work like that!
